# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-12 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPenduduk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nik', models.CharField(max_length=16)),
                ('nama', models.CharField(max_length=100)),
                ('tempat', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], default='Laki-Laki', max_length=50)),
                ('alamat', models.CharField(max_length=100)),
                ('dusun', models.CharField(choices=[('GAPIT', 'GAPIT'), ('GAPIT TIMUR', 'GAPIT TIMUR'), ('ABADI', 'ABADI'), ('NYARINYING', 'NYARINYING')], default='GAPIT', max_length=100)),
                ('agama', models.CharField(choices=[('ISLAM', 'ISLAM'), ('KRISTEN', 'KRISTEN'), ('KATOLIK', 'KATOLIK'), ('HINDU', 'HINDU'), ('BUDHA', 'BUDHA'), ('KONGHUCU', 'KONGHUCU')], default='ISLAM', max_length=100)),
                ('pekerjaan', models.CharField(choices=[('Belum Bekerja', 'Belum Bekerja'), ('Pelajar/Mahasiswa', 'Pelajar/Mahasiswa'), ('Petani/Pekebun', 'Petani/Pekebun'), ('Peternak', 'Peternak'), ('Wiraswasta', 'Wiraswasta'), ('Wirausaha', 'Wirausaha'), ('Pegawai Swasta', 'Pegawai Swasta'), ('Pegawai Negeri', 'Pegawai Negeri'), ('URT', 'URT')], default='Belum Bekerja', max_length=100)),
                ('status', models.CharField(choices=[('Belum Bekerja', 'Belum Bekerja'), ('Pelajar/Mahasiswa', 'Pelajar/Mahasiswa'), ('Petani/Pekebun', 'Petani/Pekebun'), ('Peternak', 'Peternak'), ('Wiraswasta', 'Wiraswasta'), ('Wirausaha', 'Wirausaha'), ('Pegawai Swasta', 'Pegawai Swasta'), ('Pegawai Negeri', 'Pegawai Negeri'), ('URT', 'URT')], default='Belum Kawin', max_length=100)),
                ('pendidikan_terakhir', models.CharField(choices=[('Tidak Tamat SD', 'Tidak Tamat SD'), ('Tamat SD', 'Tamat SD'), ('Tamat SMP', 'Tamat SMP'), ('Tamat SMA', 'Tamat SMA'), ('Diploma 1', 'Diploma 1'), ('Diploma 2', 'Diploma 2'), ('Diploma 3', 'Diploma 3'), ('Strata 1', 'Strata 1'), ('Strata 2', 'Strata 2'), ('Strata 3', 'Strata 3')], default='Tidak Tamat SD', max_length=100)),
            ],
        ),
    ]
