# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-12 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datapenduduk', '0001_initial'),
        ('datakartukeluarga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnggotaKeluarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anggotakeluarga_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datapenduduk.DataPenduduk')),
                ('kepala_keluarga_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datakartukeluarga.DataKartuKeluarga')),
            ],
        ),
    ]
