# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-13 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datakartukeluarga', '0002_anggotakeluarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggotakeluarga',
            name='status',
            field=models.CharField(choices=[('Istri', 'Istri'), ('Anak Kandung', 'Anak Kandung'), ('Anak Tiri', 'Anak Tiri')], default='Istri', max_length=100),
        ),
    ]
