# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-17 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datakartukeluarga', '0003_anggotakeluarga_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggotakeluarga',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
